### ISSUE TITLE
[BUG] vertical FD not working properly

### ISSUE THREAD

**Issue by MapleNAV-TCASFAULT** [flybywiresim/a32nx#1207]
**Mod Version**

Master

**Describe the bug**

The vertical FDs do not point far up enough during THR CLB. 

**To Reproduce**

1.Start a normal flight with thr clb on the fma
2.
3.

**Expected behavior**

When the throttles are decreased to CL the FDs should point down a little bit and when the aircraft reaches the target speed it should point back up to maintain the speed.

**Actual behavior**

When the throttles are decreased to CL the FDs point down a little bit to speed up the aircraft. It does but it never points back up to maintain the target speed, it will only do it for a slight second if you pass the target speed. The FDs will only work properly only when the AP is engaged

**References**

**Additional context**

https://www.youtube.com/watch?v=n3TJMro_NzA&ab_channel=baixadoetravado @4:48 and onwards should be like that

Was this working before/when did the issue start occurring?
After 1.9.3
Is this a problem in the vanilla unmodded game?
Yes

Discord username (if different from GitHub): ChristopherXie#3904

**Comment by ACSoft47** [comment]
In my case, this is the different anomaly I experenced:
I was on the glide stabilized on ILS approach at aprox 15 nm from landing and decided to test a manual landing from here. So I simply disconnected the AP and was surprised to see the FD neddle for the vertical axis (the horizontal bar) to leave the center and going up progressively. By curiosity, I corrected by going up, to see what happen and obviously, I was loosing the glideslope, going over it, like it was attested by the ILS magenta vertical marker. Finally, I ignored the FD vertical neddle and used the ILS magenta marker instead (not easy !) to successfully land.

**Comment by Mariolink123** [comment]
My experience with the FD vertical bar, is the same for approach, it simply levels the plane when AP isn't engaged however I do actually find it very useful for flaring.

**Comment by panzerdemon320** [comment]
I think this is to do with the THR CLB logic as the thrust can be reduced and is not fixed causing the FD to fluctuate all over the place. So I think when the FBW team fix the variable THR CLB, it should be fixed.

**Comment by MisterChocker** [comment]
game update improved this
