### ISSUE TITLE
Aircraft Initially Banks In Wrong Direction When Reaching Waypoints

### ISSUE THREAD

**Issue by kgaviation** [flybywiresim/a32nx#4163]
**Mod Version**

Custom/Experimental Version

**Describe the bug**

With the aircraft flying on AP, whenever it reaches a waypoint, the aircraft banks initially banks in the wrong direction for a few seconds before banking in the correct direction. This is with the aircraft on NAV mode.

**To Reproduce**

1. Create a flight plan using the worldmap feature in the menu (I used PHNL-KSJC) and start cold and dark at the gate
2. Engage NAV mode so that the aircraft will follow the FP when AP is engaged
3. After takeoff, engage AP when appropriate and allow the aircraft to follow the FP
4. Notice that the aircraft will tend to bank in the wrong direction when it reaches a waypoint before it will then bank the opposite direction to correct itself.

**Expected behavior**

When the aircraft is in NAV mode and following the FP with AP engaged, the aircraft should bank in the correct direction that the FP indicates when it reaches a waypoint. It should not bank in the wrong direction initially and then have to correct itself.

**Actual behavior**

After starting cold and dark from the gate at PHNL (Honolulu) and after creating a flight plan in the world map menu, I departed PHNL. After departure and during climb, I engaged the AP. It smoothly transitioned to AP, but upon reaching each subsequent waypoint along the route, it banks in the wrong direction initially. If the aircraft is supposed to bank left, it will bank right first and vice versa. The aircraft does continue following the FP correctly, but upon reaching every waypoint it behaves this way.

**References**

**Additional context**

Was this working before/when did the issue start occurring?
Yes. It started when I installed the new custom/experimental version.

Is this a problem in the vanilla unmodded game?
Not sure since I don't fly the default/vanille A320.

Discord username (if different from GitHub):

**Comment by kgaviation** [comment]
This is not a duplicate issue/bug. Do not close this issue. This is a newly discovered bug from the latest custom/experimental build of the mod with the new AP system. This issue has also been confirmed over on the MSFS forum today.

Please read my description of the bug carefully before deciding to close it or deem it a duplicate.

Again, this is not the same issue (4110) I posted on here earlier this week.

**Comment by Saschl** [comment]
This issue is known and should be resolved with the latest experimental. Please try updating.

**Comment by MisterChocker** [comment]
The banking is due to incomplete (wip) LNAV.
Since it's a known issue (see documentation) I'll close this issue.

**Comment by kgaviation** [comment]
My bad. There was earlier confusion from a separate, similar issue that was reported last week. 

Thank you all for the response. I will try installing the latest experimental version before my next flight.

**Comment by Saschl** [comment]
No worries, your report was really good.

**Comment by kgaviation** [comment]
Thanks, I tried to be as detailed and thorough as possible. Still getting used to posting about bugs on here.
