### ISSUE TITLE
T.O Config on 2nd flight

### ISSUE THREAD

**Issue by Keight8** [flybywiresim/a32nx#7998]
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2023-04-27T21:19:23+00:00",
    "ref": "refs/heads/experimental",
    "sha": "c907a0913975558481d0988df291df0d96a030d4",
    "actor": "BlueberryKing",
    "event_name": "manual",
    "pretty_release_name": "experimental:c907a091",
    "version": "v0.10.0-exp.c907a09"
}
```

### Describe the bug

T.O Config ECAM memo always shows  "Normal" on a second and subsequent flights.

### Expected behavior

"Test" before depressing T.O Config test pushbutton and "Normal" after.

### Steps to reproduce

Fly first leg, land, park. Start 2nd flight and check the ECAM memo during taxi.

### Discord Username (optional)

K8#4795

**Comment by hvfalcao** [comment]
> ### Aircraft Version
> Experimental
> 
> ### Build info
> {
>     "built": "2023-04-27T21:19:23+00:00",
>     "ref": "refs/heads/experimental",
>     "sha": "c907a0913975558481d0988df291df0d96a030d4",
>     "actor": "BlueberryKing",
>     "event_name": "manual",
>     "pretty_release_name": "experimental:c907a091",
>     "version": "v0.10.0-exp.c907a09"
> }
> ### Describe the bug
> T.O Config ECAM memo always shows "Normal" on a second and subsequent flights.
> 
> ### Expected behavior
> "Test" before depressing T.O Config test pushbutton and "Normal" after.
> 
> ### Steps to reproduce
> Fly first leg, land, park. Start 2nd flight and check the ECAM memo during taxi out.
> 
> ### References (optional)
> _No response_
> 
> ### Additional info (optional)
> _No response_
> 
> ### Discord Username (optional)
> K8#4795

**Comment by hvfalcao** [comment]
{
    "built": "2026-01-18T17:30:24+00:00",
    "ref": "refs/heads/master",
    "sha": "a176cff04a75134ef7b2c3e12e47fc4278ebec4e",
    "actor": "BravoMike99",
    "event_name": "manual",
    "pretty_release_name": "master:a176cff0",
    "version": "a32nx-v0.15.0-dev.a176cff"
}

Old bug, not fixed yet in the latest dev version. Same bug, behavior and steps...

**Comment by ghostxyz990** [comment]
https://github.com/flybywiresim/aircraft/pull/10165
This was fixed a while ago

**Comment by hvfalcao** [comment]
ok... so its mandatory to shutdown de engines after each landing to reset? That's the expected behavior?

**Comment by BravoMike99** [comment]
It only resets once the takeoff config status stops being normal or in the fwc "cruise phase", that's how it is implemented on the A32NX. Is it not working for you? The 380x on the other-hand may still have that bug but that would require a new issue

**Comment by hvfalcao** [comment]
It works for the non normal takeoff config alert, it will alert (red) if the flaps are set to 0 for example, but it won't reset the TO config ecam list with green or blue items to check again. Just to make clear, this happens in cycle TO and landings without gate turnarounds, engines and electrical keep running. 

<img width="310" height="218" alt="Image" src="https://github.com/user-attachments/assets/4d33ed2b-e0f7-41db-8009-8966d6975b68" />

**Comment by BravoMike99** [comment]
> It works for the non normal takeoff config alert, it will alert (red) if the flaps are set to 0 for example, but it won't reset the TO config ecam list with green or blue items to check again. Just to make clear, this happens in cycle TO and landings without gate turnarounds, engines and electrical keep running.
> <img alt="Image" width="310" height="218" src="https://private-user-images.githubusercontent.com/5053785/537776690-4d33ed2b-e0f7-41db-8009-8966d6975b68.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg5NTE3NjksIm5iZiI6MTc2ODk1MTQ2OSwicGF0aCI6Ii81MDUzNzg1LzUzNzc3NjY5MC00ZDMzZWQyYi1lMGY3LTQxZGItODAwOS04OTY2ZDY5NzViNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAxMjBUMjMyNDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ2N2Y0NWU1ZTRmNDUwMjc2YWFlNzUyOTJlMTkzMTg3YWUwNmUyZTM0MDZkZDg5NThkZTBmYTQ5M2E3YTA2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CVu-OVF-PHXaLAbRGN7QE-2Ns0rorlEOCq0Hq4kiebE">

Ah, you mean that the list does not appear? I just did a quick pattern and noticed that it does not appear again upon pressing TO CONF test. Ill create a new issue about this and close this one if that's what you saw.

**Comment by hvfalcao** [comment]
yep! you got it... thank you
